// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Torgeir Børresen <tb@starkad.no>
//
// Reference-vector generator for s2rst differential tests. It uses the Go S2
// implementation (github.com/golang/geo) as an independent oracle: it generates
// inputs, computes the reference answer, and writes CSV that
// core/tests/go_cross_validation.rs diffs the Rust implementation against.
//
// Deterministic (fixed seed) so regenerating produces identical output. See
// tools/refgen/README.md. Run: `go run . > ../../core/tests/data/go_test_vectors.csv`
package main

import (
	"bufio"
	"fmt"
	"math"
	"math/rand"
	"os"
	"strconv"

	"github.com/golang/geo/r3"
	"github.com/golang/geo/s2"
)

// f formats a float64 with enough precision to round-trip exactly (17 figures).
func f(v float64) string { return strconv.FormatFloat(v, 'g', 17, 64) }

// b2i maps a bool to 0/1.
func b2i(b bool) int {
	if b {
		return 1
	}
	return 0
}

func randPoint(rng *rand.Rand) s2.Point {
	// Uniform on the sphere via a normalized Gaussian.
	v := r3.Vector{X: rng.NormFloat64(), Y: rng.NormFloat64(), Z: rng.NormFloat64()}
	return s2.Point{Vector: v.Normalize()}
}

func main() {
	rng := rand.New(rand.NewSource(0x52715271))
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprintln(w, "# Generated by tools/refgen (oracle: github.com/golang/geo). Do not edit by hand.")

	// ── ROBUST_SIGN ──────────────────────────────────────────────────────
	// a,b,c (each a normalized unit vector) -> Direction in {-1,0,1}.
	// The orientation predicate is exact; its result must match bit-for-bit.
	fmt.Fprintln(w, "# ROBUST_SIGN")
	emit := func(a, b, c s2.Point) {
		fmt.Fprintf(w, "%s,%s,%s,%s,%s,%s,%s,%s,%s,%d\n",
			f(a.X), f(a.Y), f(a.Z),
			f(b.X), f(b.Y), f(b.Z),
			f(c.X), f(c.Y), f(c.Z),
			int(s2.RobustSign(a, b, c)))
	}

	// Broad random coverage.
	for i := 0; i < 5000; i++ {
		emit(randPoint(rng), randPoint(rng), randPoint(rng))
	}

	// Near-collinear triples: c sits on the great circle through a,b and is then
	// pushed off by a tiny perpendicular amount (1e-8 .. ~1e-20 rad). These drive
	// the fast determinant toward zero and exercise the exact-arithmetic fallback.
	for i := 0; i < 5000; i++ {
		a := randPoint(rng)
		b := randPoint(rng)
		t := rng.Float64()
		onCircle := a.Mul(1 - t).Add(b.Mul(t)).Normalize() // lies in the a,b plane
		perp := a.Cross(b.Vector).Normalize()
		eps := math.Pow(10, -8-12*rng.Float64())
		c := s2.Point{Vector: onCircle.Add(perp.Mul(eps)).Normalize()}
		emit(a, b, s2.Point{Vector: onCircle})
		emit(a, b, c)
	}

	// Degenerate: two coincident points (must be Indeterminate).
	for i := 0; i < 100; i++ {
		a := randPoint(rng)
		b := randPoint(rng)
		emit(a, a, b)
		emit(a, b, a)
		emit(b, a, a)
	}

	// ── EDGE_CROSSING ────────────────────────────────────────────────────
	// Edge AB vs edge CD -> (CrossingSign in {0=Cross,1=MaybeCross,2=DoNotCross},
	// EdgeOrVertexCrossing in {0,1}). Both are exact/robust predicates and must
	// match bit-for-bit.
	fmt.Fprintln(w, "# EDGE_CROSSING")
	emitX := func(a, b, c, d s2.Point) {
		fmt.Fprintf(w, "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%d,%d\n",
			f(a.X), f(a.Y), f(a.Z), f(b.X), f(b.Y), f(b.Z),
			f(c.X), f(c.Y), f(c.Z), f(d.X), f(d.Y), f(d.Z),
			int(s2.CrossingSign(a, b, c, d)),
			b2i(s2.EdgeOrVertexCrossing(a, b, c, d)))
	}
	// Orthonormal tangent directions at x.
	tangents := func(x s2.Point) (r3.Vector, r3.Vector) {
		r := randPoint(rng)
		t1 := r.Sub(x.Mul(x.Dot(r.Vector))).Normalize()
		t2 := x.Cross(t1).Normalize()
		return t1, t2
	}
	off := func(x s2.Point, t r3.Vector, e float64) s2.Point {
		return s2.Point{Vector: x.Add(t.Mul(e)).Normalize()}
	}

	// Random edges (mostly DoNotCross, some Cross).
	for i := 0; i < 4000; i++ {
		emitX(randPoint(rng), randPoint(rng), randPoint(rng), randPoint(rng))
	}
	// Edges straddling a common point x along perpendicular tangents -> Cross.
	// Sweep the half-length 1e-1 .. 1e-6 to stress the robust predicate.
	for i := 0; i < 3000; i++ {
		x := randPoint(rng)
		t1, t2 := tangents(x)
		e := math.Pow(10, -1-5*rng.Float64())
		emitX(off(x, t1, e), off(x, t1, -e), off(x, t2, e), off(x, t2, -e))
	}
	// Shared endpoint between the two edges -> MaybeCross + vertex tie-break.
	for i := 0; i < 1500; i++ {
		a, b, d := randPoint(rng), randPoint(rng), randPoint(rng)
		emitX(a, b, b, d) // b == c
		emitX(a, b, d, a) // a == d
	}
	// Near-miss: cd is shifted off x so the edges nearly-but-don't cross.
	for i := 0; i < 1500; i++ {
		x := randPoint(rng)
		t1, t2 := tangents(x)
		e := math.Pow(10, -1-5*rng.Float64())
		emitX(off(x, t1, e), off(x, t1, -e), off(x, t2, 2*e), off(x, t2, e))
	}

	// ── POINT_AREA ───────────────────────────────────────────────────────
	// a,b,c -> spherical triangle area (l'Huilier). Numeric; compared within a
	// tolerance (Go and Rust use different libm, so a few ULPs may differ).
	fmt.Fprintln(w, "# POINT_AREA")
	emitArea := func(a, b, c s2.Point) {
		fmt.Fprintf(w, "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
			f(a.X), f(a.Y), f(a.Z), f(b.X), f(b.Y), f(b.Z), f(c.X), f(c.Y), f(c.Z),
			f(s2.PointArea(a, b, c)))
	}
	for i := 0; i < 4000; i++ {
		emitArea(randPoint(rng), randPoint(rng), randPoint(rng))
	}
	// Small triangles near a point (precision stress across scales).
	for i := 0; i < 2000; i++ {
		a := randPoint(rng)
		t1, t2 := tangents(a)
		e := math.Pow(10, -1-5*rng.Float64())
		emitArea(a, off(a, t1, e), off(a, t2, e))
	}

	// ── EDGE_DISTANCE ────────────────────────────────────────────────────
	// x,a,b -> minimum distance (radians) from x to segment ab.
	fmt.Fprintln(w, "# EDGE_DISTANCE")
	emitDist := func(x, a, b s2.Point) {
		fmt.Fprintf(w, "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
			f(x.X), f(x.Y), f(x.Z), f(a.X), f(a.Y), f(a.Z), f(b.X), f(b.Y), f(b.Z),
			f(s2.DistanceFromSegment(x, a, b).Radians()))
	}
	for i := 0; i < 4000; i++ {
		emitDist(randPoint(rng), randPoint(rng), randPoint(rng))
	}
	// x placed just off the segment interior (small perpendicular offsets).
	for i := 0; i < 2000; i++ {
		a := randPoint(rng)
		b := randPoint(rng)
		mid := s2.Point{Vector: a.Add(b.Vector).Normalize()}
		perp, _ := tangents(mid)
		e := math.Pow(10, -1-5*rng.Float64())
		emitDist(off(mid, perp, e), a, b)
	}

	// ── CLOSEST_EDGE ─────────────────────────────────────────────────────
	// Index a polyline of N points; query the minimum distance (radians) from a
	// point to its nearest edge. Exercises the ShapeIndex + query layer. Numeric
	// (within tolerance). Row: N, N points, query point, distance.
	fmt.Fprintln(w, "# CLOSEST_EDGE")
	for i := 0; i < 3000; i++ {
		n := 2 + rng.Intn(19) // 2..20 polyline points
		pts := make([]s2.Point, n)
		for j := range pts {
			pts[j] = randPoint(rng)
		}
		pl := s2.Polyline(pts)
		index := s2.NewShapeIndex()
		index.Add(&pl)
		q := s2.NewClosestEdgeQuery(index, nil)
		query := randPoint(rng)
		dist := q.Distance(s2.NewMinDistanceToPointTarget(query)).Angle().Radians()
		fmt.Fprintf(w, "%d", n)
		for _, p := range pts {
			fmt.Fprintf(w, ",%s,%s,%s", f(p.X), f(p.Y), f(p.Z))
		}
		fmt.Fprintf(w, ",%s,%s,%s,%s\n", f(query.X), f(query.Y), f(query.Z), f(dist))
	}

	// ── POLYLINE_LENGTH ──────────────────────────────────────────────────
	// Polyline of N points -> total length (radians). Row: N, N points, length.
	fmt.Fprintln(w, "# POLYLINE_LENGTH")
	for i := 0; i < 3000; i++ {
		n := 2 + rng.Intn(19)
		pts := make([]s2.Point, n)
		for j := range pts {
			pts[j] = randPoint(rng)
		}
		pl := s2.Polyline(pts)
		fmt.Fprintf(w, "%d", n)
		for _, p := range pts {
			fmt.Fprintf(w, ",%s,%s,%s", f(p.X), f(p.Y), f(p.Z))
		}
		fmt.Fprintf(w, ",%s\n", f(pl.Length().Radians()))
	}

	// ── LOOP_AREA ────────────────────────────────────────────────────────
	// A small regular polygon around a centre -> area (steradians). Simple loops
	// keep the area well-defined. Row: N, N points, area.
	fmt.Fprintln(w, "# LOOP_AREA")
	for i := 0; i < 3000; i++ {
		center := randPoint(rng)
		t1, t2 := tangents(center)
		k := 3 + rng.Intn(6)                          // 3..8 vertices
		radius := math.Pow(10, -0.3-2*rng.Float64()) // ~0.5 .. 0.005 rad
		pts := make([]s2.Point, k)
		for j := 0; j < k; j++ {
			ang := 2 * math.Pi * float64(j) / float64(k)
			dir := t1.Mul(math.Cos(ang)).Add(t2.Mul(math.Sin(ang)))
			pts[j] = off(center, dir, radius)
		}
		l := s2.LoopFromPoints(pts)
		fmt.Fprintf(w, "%d", k)
		for _, p := range pts {
			fmt.Fprintf(w, ",%s,%s,%s", f(p.X), f(p.Y), f(p.Z))
		}
		fmt.Fprintf(w, ",%s\n", f(l.Area()))
	}
}
