#!/usr/bin/env python3
"""Extract the graph_edge_clipper boolean-op regression inputs from the Rust
test source into a flat, language-neutral data file.

The `test_bug*` / `test_union_with_ambiguous_crossings` cases in
`core/src/s2/polygon.rs` embed their input polygons as literal `pt(x, y, z)`
coordinates. This script lifts them verbatim (no re-typing) into
`core/tests/data/boolean_op_inputs.txt`, which is the single source of truth
consumed by both the C++ oracle generator (`generate_boolean_op.cc`) and the
Rust differential harness (`core/tests/cpp_boolean_op_diff.rs`).

Run from the repo root:  python3 tools/refgen-cpp/extract_boolean_op_inputs.py

Output format (one case after another):

    CASE <name> <op>
    A <num_loops>
    LOOP <num_vertices>
    <x> <y> <z>
    ...
    B <num_loops>
    LOOP <num_vertices>
    <x> <y> <z>
    ...
    END
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "core" / "src" / "s2" / "polygon.rs"
OUT = ROOT / "core" / "tests" / "data" / "boolean_op_inputs.txt"

PT = re.compile(
    r"pt\(\s*(-?[0-9.eE+]+)\s*,\s*(-?[0-9.eE+]+)\s*,\s*(-?[0-9.eE+]+)\s*,?\s*\)"
)
# `Point(Vector::new(x, y, z))` — raw, *non-normalized* points (matches C++
# S2Point). Distinct from pt()/Point::from_coords, which normalizes.
VEC = re.compile(
    r"Vector::new\(\s*(-?[0-9.eE+]+)\s*,\s*(-?[0-9.eE+]+)\s*,\s*(-?[0-9.eE+]+)\s*,?\s*\)"
)


def match_delim(text, start, open_ch, close_ch):
    """Return index just past the close that balances the open at `start`."""
    assert text[start] == open_ch, (text[start], start)
    depth = 0
    i = start
    while i < len(text):
        c = text[i]
        if c == open_ch:
            depth += 1
        elif c == close_ch:
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError("unbalanced")


def fn_body(text, name):
    """Return the brace-balanced body of `fn <name>(`."""
    m = re.search(r"\bfn " + re.escape(name) + r"\s*\(", text)
    if not m:
        raise ValueError(f"fn {name} not found")
    brace = text.index("{", m.end())
    return text[brace : match_delim(text, brace, "{", "}")]


def loops_in_vec(region, pat):
    """Split a `vec![ vec![...], vec![...] ]` region into per-loop triples.

    Handles multi-loop operands (e.g. bug4 A) by matching each inner `vec![ ]`
    at bracket depth, then pulling `pat` triples from each loop.
    """
    outer = region.index("[")
    inner = region[outer + 1 : match_delim(region, outer, "[", "]") - 1]
    loops, i = [], 0
    while True:
        v = inner.find("vec![", i)
        if v < 0:
            break
        lb = v + len("vec!")
        end = match_delim(inner, lb, "[", "]")
        loops.append([tuple(g) for g in pat.findall(inner[lb:end])])
        i = end
    return loops


def parse_case(body):
    """Return (normalize, a_loops, b_loops) for one test body, supporting both
    the `make_polygon_from_loops(vec![vec![pt(...)]])` style (normalized via
    `Point::from_coords`) and the `Point(Vector::new(...))` style (raw)."""
    if "make_polygon_from_loops" in body:
        a_start = body.index("make_polygon_from_loops")
        b_start = body.index("make_polygon_from_loops", a_start + 1)
        a = loops_in_vec(body[a_start:b_start], PT)
        b = loops_in_vec(body[b_start:], PT)
        return 1, a, b
    # `let a_vertices = vec![ Point(Vector::new(...)), ... ];` (single loop each)
    a_at = body.index("a_vertices")
    b_at = body.index("b_vertices")
    a = [[tuple(g) for g in VEC.findall(body[a_at:b_at])]]
    b = [[tuple(g) for g in VEC.findall(body[b_at:])]]
    return 0, a, b


def main():
    text = SRC.read_text()
    cases = [f"test_bug{i}" for i in range(1, 13)] + [
        "test_union_with_ambiguous_crossings"
    ]
    lines = [
        "# Boolean-op regression inputs extracted from core/src/s2/polygon.rs.",
        "# Generated by tools/refgen-cpp/extract_boolean_op_inputs.py — do not edit by hand.",
    ]
    for name in cases:
        body = fn_body(text, name)
        op = re.search(
            r"Polygon::(union|intersection|difference|symmetric_difference)", body
        ).group(1)
        normalize, a_loops, b_loops = parse_case(body)
        short = name.replace("test_", "")
        lines.append(f"CASE {short} {op} {normalize}")
        for label, loops in (("A", a_loops), ("B", b_loops)):
            lines.append(f"{label} {len(loops)}")
            for loop in loops:
                lines.append(f"LOOP {len(loop)}")
                for x, y, z in loop:
                    lines.append(f"{x} {y} {z}")
        lines.append("END")
        print(
            f"{name}: op={op} norm={normalize} "
            f"A={[len(l) for l in a_loops]} B={[len(l) for l in b_loops]}",
            file=sys.stderr,
        )
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
