// Oracle generator for the graph_edge_clipper boolean-op regression cases.
//
// Reads core/tests/data/boolean_op_inputs.txt (produced by
// extract_boolean_op_inputs.py from the Rust tests) and, for each case, runs
// the operation through google/s2geometry — the reference implementation — and
// emits the result summary to stdout. The committed output
// (core/tests/data/cpp_boolean_op_vectors.txt) is diffed by
// core/tests/cpp_boolean_op_diff.rs with no C++ toolchain in CI.
//
// Usage: ./generate_boolean_op <path-to-boolean_op_inputs.txt>

#include <cstdio>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include "s2/s2debug.h"
#include "s2/s2loop.h"
#include "s2/s2point.h"
#include "s2/s2polygon.h"

namespace {

struct Loop {
  std::vector<S2Point> pts;
};
struct Poly {
  std::vector<Loop> loops;
};
struct Case {
  std::string name;
  std::string op;
  int normalize = 0;
  Poly a, b;
};

std::vector<Case> ParseInputs(std::istream& in) {
  std::vector<Case> cases;
  std::string tok;
  while (in >> tok) {
    if (tok == "#") {  // comment line
      std::string rest;
      std::getline(in, rest);
      continue;
    }
    if (tok != "CASE") {
      // Skip stray tokens defensively.
      std::string rest;
      std::getline(in, rest);
      continue;
    }
    Case c;
    in >> c.name >> c.op >> c.normalize;
    for (Poly* p : {&c.a, &c.b}) {
      std::string label;
      int num_loops = 0;
      in >> label >> num_loops;  // "A <n>" / "B <n>"
      for (int i = 0; i < num_loops; ++i) {
        std::string loop_kw;
        int nv = 0;
        in >> loop_kw >> nv;  // "LOOP <n>"
        Loop loop;
        for (int v = 0; v < nv; ++v) {
          double x, y, z;
          in >> x >> y >> z;
          loop.pts.push_back(S2Point(x, y, z));
        }
        p->loops.push_back(std::move(loop));
      }
    }
    std::string end_kw;
    in >> end_kw;  // "END"
    cases.push_back(std::move(c));
  }
  return cases;
}

std::unique_ptr<S2Polygon> Build(const Poly& p, int normalize) {
  std::vector<std::unique_ptr<S2Loop>> loops;
  for (const auto& lp : p.loops) {
    std::vector<S2Point> v;
    v.reserve(lp.pts.size());
    for (const S2Point& pt : lp.pts) {
      v.push_back(normalize ? pt.Normalize() : pt);
    }
    loops.push_back(std::make_unique<S2Loop>(v, S2Debug::DISABLE));
  }
  auto poly = std::make_unique<S2Polygon>();
  poly->set_s2debug_override(S2Debug::DISABLE);
  poly->InitNested(std::move(loops));
  return poly;
}

}  // namespace

int main(int argc, char** argv) {
  std::string path =
      argc > 1 ? argv[1] : "core/tests/data/boolean_op_inputs.txt";
  std::ifstream in(path);
  if (!in) {
    std::cerr << "cannot open " << path << "\n";
    return 1;
  }
  std::vector<Case> cases = ParseInputs(in);

  std::cout << "# Generated by tools/refgen-cpp/generate_boolean_op "
               "(oracle: google/s2geometry). Do not edit by hand.\n";
  std::cout << "# Per case: is the boolean-op output empty, and its loop/"
               "vertex/area summary.\n";
  std::cout.precision(17);
  for (const Case& c : cases) {
    auto a = Build(c.a, c.normalize);
    auto b = Build(c.b, c.normalize);
    S2Polygon out;
    out.set_s2debug_override(S2Debug::DISABLE);
    if (c.op == "union") {
      out.InitToUnion(*a, *b);
    } else if (c.op == "intersection") {
      out.InitToIntersection(*a, *b);
    } else if (c.op == "difference") {
      out.InitToDifference(*a, *b);
    } else {
      out.InitToSymmetricDifference(*a, *b);
    }
    std::cout << "CASE " << c.name << " " << c.op << "\n";
    std::cout << "RESULT empty=" << (out.is_empty() ? 1 : 0)
              << " loops=" << out.num_loops()
              << " vertices=" << out.num_vertices()
              << " area=" << out.GetArea() << "\n";
  }
  return 0;
}
