// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Torgeir Børresen <tb@starkad.no>
//
// Reference-vector generator for s2rst CellId differential tests, using the C++
// reference implementation (google/s2geometry) as the oracle. Emits CSV that
// core/tests/cpp_cellid_diff.rs diffs the Rust CellId implementation against.
// Deterministic (fixed seed). See tools/refgen-cpp/README.md.

#include <cstdint>
#include <cstdio>
#include <random>

#include "s2/s2cell_id.h"
#include "s2/s2point.h"

namespace {

std::mt19937_64 rng(0x52715271ULL);
std::normal_distribution<double> gauss(0.0, 1.0);

S2Point RandPoint() {
  S2Point p(gauss(rng), gauss(rng), gauss(rng));
  return p.Normalize();
}

// A random cell at a random level (0..30).
S2CellId RandCell() {
  S2CellId leaf(RandPoint());
  int level = static_cast<int>(rng() % 31);
  return leaf.parent(level);
}

unsigned long long Id(S2CellId c) { return static_cast<unsigned long long>(c.id()); }

}  // namespace

int main() {
  std::printf(
      "# Generated by tools/refgen-cpp (oracle: google/s2geometry). Do not edit by hand.\n");

  // id -> the four edge-neighbour ids.
  std::printf("# CELLID_EDGE_NEIGHBORS\n");
  for (int i = 0; i < 5000; ++i) {
    S2CellId c = RandCell();
    S2CellId nb[4];
    c.GetEdgeNeighbors(nb);
    std::printf("%llu,%llu,%llu,%llu,%llu\n", Id(c), Id(nb[0]), Id(nb[1]), Id(nb[2]), Id(nb[3]));
  }

  // id -> range_min, range_max (the leaf-cell interval covered by this cell).
  std::printf("# CELLID_RANGE\n");
  for (int i = 0; i < 5000; ++i) {
    S2CellId c = RandCell();
    std::printf("%llu,%llu,%llu\n", Id(c), Id(c.range_min()), Id(c.range_max()));
  }

  // a,b -> contains(a,b), intersects(a,b). b is drawn from related and unrelated
  // cells so all four (contains, intersects) combinations occur.
  std::printf("# CELLID_CONTAINS\n");
  for (int i = 0; i < 5000; ++i) {
    S2CellId a = RandCell();
    S2CellId b;
    switch (rng() % 4) {
      case 0:  // an immediate child of a (so a contains b)
        b = a.is_leaf() ? a : a.child(static_cast<int>(rng() % 4));
        break;
      case 1:  // an ancestor of a (so b contains a)
        b = a.parent(static_cast<int>(rng() % (a.level() + 1)));
        break;
      case 2: {  // an edge neighbour
        S2CellId nb[4];
        a.GetEdgeNeighbors(nb);
        b = nb[rng() % 4];
        break;
      }
      default:  // an unrelated random cell
        b = RandCell();
        break;
    }
    std::printf("%llu,%llu,%d,%d\n", Id(a), Id(b), a.contains(b) ? 1 : 0, a.intersects(b) ? 1 : 0);
  }

  // A non-leaf cell -> its four children.
  std::printf("# CELLID_CHILDREN\n");
  for (int i = 0; i < 5000; ++i) {
    S2CellId c = RandCell();
    while (c.is_leaf()) c = RandCell();  // children require a non-leaf cell
    std::printf("%llu,%llu,%llu,%llu,%llu\n", Id(c), Id(c.child(0)), Id(c.child(1)), Id(c.child(2)),
        Id(c.child(3)));
  }

  // cell -> (face, i, j, orientation): the core (face, i, j) <-> Hilbert mapping.
  std::printf("# CELLID_FACE_IJ\n");
  for (int i = 0; i < 5000; ++i) {
    S2CellId c = RandCell();
    int ci, cj, orientation;
    int face = c.ToFaceIJOrientation(&ci, &cj, &orientation);
    std::printf("%llu,%d,%d,%d,%d\n", Id(c), face, ci, cj, orientation);
  }
  return 0;
}
