# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Torgeir Børresen <tb@starkad.no>

"""Python bindings for the s2rst spherical geometry library."""

from collections.abc import Sequence

from ._core import (
    __version__,
    Angle,
    Cap,
    Cell,
    CellId,
    CellUnion,
    ChordAngle,
    Earth,
    Edge,
    EdgeVectorShape,
    LatLng,
    LaxLoop,
    LaxPolygon,
    LaxPolyline,
    Loop,
    Matrix3x3,
    PointVector,
    Polygon,
    Polyline,
    R1Interval,
    R2Point,
    R2Rect,
    Rect,
    ReferencePoint,
    RegionCoverer,
    S1Interval,
    S2Builder,
    S2Point,
    Shape,
    ShapeIndex,
    Vector,
    decode_cell_union,
    decode_loop,
    decode_polygon,
    decode_polyline,
    encode,
    latlng_to_string,
    loop_to_string,
    make_loop,
    make_polygon,
    make_polyline,
    parse_latlngs,
    parse_point,
    parse_points,
    point_to_string,
    points_to_string,
    polygon_to_string,
    polyline_to_string,
    s2_ortho,
    s2_rotate,
)

# Register variable-size sequence types as Sequence virtual subclasses so
# `isinstance(x, Sequence)` returns True. Sequence has no structural
# __subclasshook__, so this registration is required even though every type
# below already has __len__, __getitem__, and __iter__.
for _cls in (
    Polyline,
    Loop,
    Polygon,
    LaxLoop,
    LaxPolyline,
    PointVector,
    EdgeVectorShape,
    CellUnion,
):
    Sequence.register(_cls)
del _cls

__all__ = [
    "Angle",
    "Cap",
    "Cell",
    "CellId",
    "CellUnion",
    "ChordAngle",
    "Earth",
    "Edge",
    "EdgeVectorShape",
    "LatLng",
    "LaxLoop",
    "LaxPolygon",
    "LaxPolyline",
    "Loop",
    "Matrix3x3",
    "PointVector",
    "Polygon",
    "Polyline",
    "R1Interval",
    "R2Point",
    "R2Rect",
    "Rect",
    "ReferencePoint",
    "RegionCoverer",
    "S1Interval",
    "S2Builder",
    "S2Point",
    "Shape",
    "ShapeIndex",
    "Vector",
    "decode_cell_union",
    "decode_loop",
    "decode_polygon",
    "decode_polyline",
    "encode",
    "latlng_to_string",
    "loop_to_string",
    "make_loop",
    "make_polygon",
    "make_polyline",
    "parse_latlngs",
    "parse_point",
    "parse_points",
    "point_to_string",
    "points_to_string",
    "polygon_to_string",
    "polyline_to_string",
    "__version__",
    "s2_ortho",
    "s2_rotate",
]
